### ISSUE TITLE
Fix exception in surface and context destructors

### ISSUE THREAD

**Issue by perey** [perey/pegl#15]
Just tried running the sample code under Pegl 0.2a1 on Raspberry Pi OS. All went well until cleanup time:
```python
>>> import pegl
...
>>> ctx.make_current(draw=surf)
>>> exit()
Exception ignored in: <function Context.__del__ at 0xb611eb20>
Traceback (most recent call last):
  File "/home/pi/pegl-test/lib/python3.9/site-packages/pegl/context.py", line 69, in __del__
  File "/home/pi/pegl-test/lib/python3.9/site-packages/pegl/egl/_common.py", line 210, in error_check
pegl.errors.NotInitializedError: 
Exception ignored in: <function Surface.__del__ at 0xb612d148>
Traceback (most recent call last):
  File "/home/pi/pegl-test/lib/python3.9/site-packages/pegl/surface.py", line 51, in __del__
  File "/home/pi/pegl-test/lib/python3.9/site-packages/pegl/egl/_common.py", line 210, in error_check
pegl.errors.NotInitializedError: 
```
Not only did two (ignored) exceptions get raised, they’re both singularly uninformative, with an apparently empty error text. I need to (a) make sure there’s a meaningful message (or else none at all?), and (b) stop it happening.

**Comment by perey** [comment]
Interestingly, this only seems to happen when entering the commands into an interactive session. Running them from a script doesn't trigger the error. Neither does wrapping them in a function, importing it into the interactive session, and running it.
